# Generated by Django 4.2.4 on 2024-03-10 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=256)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Ümumi Məlumat',
                'verbose_name_plural': 'Ümumi Məlumat',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
                ('icon_white_backround', models.ImageField(blank=True, null=True, upload_to='')),
                ('icon_black_backround', models.ImageField(blank=True, null=True, upload_to='')),
                ('video_uzerinde_olsun', models.BooleanField(default=False)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sosial Media Hesabı',
                'verbose_name_plural': 'Sosial Media Hesabları',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('subscribed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Abunə olmuş oxucu',
                'verbose_name_plural': 'Abunə olmuş oxucular',
            },
        ),
        migrations.CreateModel(
            name='HotTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'verbose_name': 'Seçilmiş Mövzu',
                'verbose_name_plural': 'Seçilmiş Mövzular',
            },
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
            options={
                'verbose_name': 'Seçilmiş Bloq',
                'verbose_name_plural': 'Seçilmiş Bloqlar',
            },
        ),
    ]
