# Generated by Django 4.2.4 on 2023-08-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='logo',
            new_name='icon',
        ),
    ]
