# Generated by Django 4.2.4 on 2023-08-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hottopics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='icon',
        ),
        migrations.AddField(
            model_name='social',
            name='icon_black_backround',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='social',
            name='icon_white_backround',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='social',
            name='video_uzerinde_olsun',
            field=models.BooleanField(default=False),
        ),
    ]
