# Generated by Django 4.2.4 on 2023-09-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_social_icon_social_icon_black_backround_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ('sort',)},
        ),
        migrations.AddField(
            model_name='social',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
