# Generated by Django 4.2.3 on 2023-10-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_social_options_social_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('short_description', models.TextField()),
            ],
        ),
    ]
