# Generated by Django 4.2.4 on 2023-11-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_telim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Telim',
        ),
    ]
