# Generated by Django 4.2.4 on 2024-02-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_category_remove_blogcategory_parent_and_more'),
        ('core', '0006_delete_telim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hottopics',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
