# Generated by Django 4.2.4 on 2024-02-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_hottopics_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featured',
            options={'verbose_name': 'Seçilmiş Bloq', 'verbose_name_plural': 'Seçilmiş Bloqlar'},
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'verbose_name': 'Ümumi Məlumat', 'verbose_name_plural': 'Ümumi Məlumat'},
        ),
        migrations.AlterModelOptions(
            name='hottopics',
            options={'verbose_name': 'Seçilmiş Mövzu', 'verbose_name_plural': 'Seçilmiş Mövzular'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Sosial Media Hesabı', 'verbose_name_plural': 'Sosial Media Hesabları'},
        ),
    ]
