# Generated by Django 4.2.4 on 2024-03-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_featured_options_alter_general_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('subscribed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Abunə olmuş oxucu',
                'verbose_name_plural': 'Abunə olmuş oxucular',
            },
        ),
    ]
