# Generated by Django 4.2.4 on 2023-08-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(default='1', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
