# Generated by Django 4.2.4 on 2023-09-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reading_time',
            field=models.CharField(default='q', max_length=256),
            preserve_default=False,
        ),
    ]
