# Generated by Django 4.2.3 on 2023-10-31 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='reading_time',
        ),
    ]
