# Generated by Django 4.2.4 on 2023-12-11 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='publish_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
