# Generated by Django 4.2.4 on 2023-12-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blogcategory_publish_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='publish_datetime',
        ),
        migrations.AddField(
            model_name='blog',
            name='publish_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
