# Generated by Django 4.2.4 on 2024-02-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_blogcategory_publish_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('sort', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Bloq kateqoriya',
                'verbose_name_plural': 'Bloq kateqoriyaları',
                'ordering': ('sort',),
            },
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
