# Generated by Django 4.2.4 on 2024-02-16 11:20

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_category_remove_blogcategory_parent_and_more'),
        ('core', '0007_alter_hottopics_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='main',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='blog.category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blog.category'),
        ),
    ]
