# Generated by Django 4.2.4 on 2024-02-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_delete_blogcategory_category_main_blog_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='main',
            new_name='parent',
        ),
    ]
