# Generated by Django 4.2.4 on 2024-02-16 12:03

import ckeditor_uploader.fields
from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_main_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cat',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
