# Generated by Django 4.2.4 on 2024-02-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_blog_cat_alter_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('position', models.CharField(max_length=256)),
                ('feedback', models.TextField()),
            ],
            options={
                'verbose_name': 'Rəy',
                'verbose_name_plural': 'Rəylər',
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Bloq yazı', 'verbose_name_plural': 'Bloq yazıları'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Bloq teq', 'verbose_name_plural': 'Bloq teqləri'},
        ),
    ]
