# Generated by Django 4.2.4 on 2024-02-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_review_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='feedback_short_version',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
