# Generated by Django 4.2.4 on 2024-02-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_review_feedback_short_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reading_time',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
