# Generated by Django 4.2.4 on 2024-02-17 12:32

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_blog_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cat',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.category'),
            preserve_default=False,
        ),
    ]
