# Generated by Django 4.2.4 on 2024-03-01 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_blog_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-id',), 'verbose_name': 'Bloq yazı', 'verbose_name_plural': 'Bloq yazıları'},
        ),
        migrations.CreateModel(
            name='SelectedBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
            options={
                'verbose_name': 'Seçilmiş Bloq yazı',
                'verbose_name_plural': 'Seçilmiş Bloq yazıları',
                'ordering': ('sort',),
            },
        ),
    ]
