# Generated by Django 4.2.4 on 2024-02-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_category_delete_eventcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('sort',), 'verbose_name': 'Tədbir', 'verbose_name_plural': 'Tədbirlər'},
        ),
    ]
