# Generated by Django 4.2.4 on 2023-11-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
