# Generated by Django 4.2.4 on 2023-11-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicecategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
