# Generated by Django 4.2.4 on 2024-02-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_service_category_delete_servicecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('sort',), 'verbose_name': 'Xidmət', 'verbose_name_plural': 'Xidmətlər'},
        ),
    ]
