# Generated by Django 4.2.4 on 2023-12-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telim',
            name='category',
        ),
        migrations.DeleteModel(
            name='TelimCategory',
        ),
    ]
