# Generated by Django 4.2.4 on 2024-02-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_telim_category_delete_telimcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telim',
            options={'ordering': ('sort',), 'verbose_name': 'Təlim', 'verbose_name_plural': 'Təlimlər'},
        ),
    ]
